---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-updater
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./cluster-updater
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
