apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: rook-ceph
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://rook.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph
  namespace: flux-system
spec:
  releaseName: rook-ceph
  chart:
    spec:
      chart: rook-ceph
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: rook-ceph
  targetNamespace: rook-ceph
  install:
    createNamespace: true
    remediation:
      retries: 3
  interval: 10m0s
  values: {}
