apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Habilita/deshabilita aplicaciones comentando líneas
resources:
  - flux-system/
  - openebs/
  - cert-manager/
  - metallb/
  - traefik/
  - cluster-updater/
  - external-dns/
  - frigate/
  #- kube-prometheus-stack/
  - openweb-ui/
  - openclaw/
  - omada
  # - authentik/
