---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: openebs
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://openebs.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openebs
  namespace: flux-system
spec:
  releaseName: openebs
  chart:
    spec:
      chart: openebs
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: openebs
  targetNamespace: openebs
  install:
    createNamespace: true
    remediation:
      retries: 1
  interval: 10m0s
  values:
    localprovisiones:
      hostpathClass:
        enabled: true
        isDefaultClass: false
