---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: traefik
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://traefik.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: flux-system
spec:
  releaseName: traefik
  chart:
    spec:
      chart: traefik
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: traefik
  targetNamespace: traefik
  install:
    createNamespace: true
    remediation:
      retries: 1
  interval: 10m0s
  values:
    ingressRoute:
      dashboard:
        enabled: true
    ports:
      omada-http:
        port: 8088
        exposedPort: 8088
        protocol: TCP
        expose:
          default: true
      omada-manage:
        port: 8043
        exposedPort: 8043
        protocol: TCP
        expose:
          default: true
      omada-portal:
        port: 8843
        exposedPort: 8843
        protocol: TCP
        expose:
          default: true
      omada27001:
        port: 27001
        exposedPort: 27001
        protocol: UDP
        expose:
          default: true
      omada29810:
        port: 29810
        exposedPort: 29810
        protocol: UDP
        expose:
          default: true
      omada19810:
        port: 19810
        exposedPort: 19810
        protocol: UDP
        expose:
          default: true
      omada29811:
        port: 29811
        exposedPort: 29811
        protocol: TCP
        expose:
          default: true
      omada29812:
        port: 29812
        exposedPort: 29812
        protocol: TCP
        expose:
          default: true
      omada29813:
        port: 29813
        exposedPort: 29813
        protocol: TCP
        expose:
          default: true
      omada29814:
        port: 29814
        exposedPort: 29814
        protocol: TCP
        expose:
          default: true
      omada29815:
        port: 29815
        exposedPort: 29815
        protocol: TCP
        expose:
          default: true
      omada29816:
        port: 29816
        exposedPort: 29816
        protocol: TCP
        expose:
          default: true
      omada29817:
        port: 29817
        exposedPort: 29817
        protocol: TCP
        expose:
          default: true
