apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
    name: authentik
    namespace: flux-system
spec:
    interval: 10m0s
    url: https://charts.goauthentik.io
sops:
    encrypted_regex: ^(data|stringData)$|password|secret_key
    lastmodified: "2026-10-08T10:58:57Z"
    mac: ENC[AES256_GCM,data:0hxUD5qfcYAE5nhlmPTsebjt9pKB91NQ9iSmeBUNLHkmsX3HMQB8u9Ox7jU/D7wCRVg3VguGqhUZexMzOhtwBiCf/a18vIfyDMItmZqVWiMlSxu0aqxLwGcIfLtDyfM5l3ivtmJpUdK10KfA/Ez+5UN5gXjeMByToTJFqRokTOQ=,iv:n+CsQmzwTWx4+/Kbfp7T0TuRKnPTj+WUyZ3LSt3MEuc=,tag:SKRhyqUNBke14OGSHA8Lcg==,type:str]
    pgp:
        - created_at: "2026-10-08T10:58:57Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DwW+vaVwrS2ISAQdAxCs2D5WaMZjss3u7ci8R7dBPMKnYHKWzDsXYXW6LMWgw
            RZzN58zjFPT7YJ+rr6joQPjTyRFhsWHLV1wfpYaqeZNAkc/oTCTxUtw+MsNeXO7x
            0l4BcKgan/Mm68A1/rwzI45/PuxDK4ZzviR/KqLooOKAoXYmBRW5kfp5odQwP9iB
            cwcnZSy9KRJ53yg56wLNHvXRd/QQSGfh1zd1vAOQtT73hmcGfeE9mV5dpoPJu7Ae
            =pA/P
            -----END PGP MESSAGE-----
          fp: B51175A0392C55BA3A9D508C914AB2CE60624E82
    version: 3.13.3
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: authentik
    namespace: flux-system
spec:
    releaseName: authentik
    chart:
        spec:
            chart: authentik
            reconcileStrategy: ChartVersion
            sourceRef:
                kind: HelmRepository
                name: authentik
    targetNamespace: authentik
    install:
        createNamespace: true
        remediation:
            retries: 1
    interval: 10m0s
    timeout: 10m
    values:
        authentik:
            secret_key: ENC[AES256_GCM,data:ePSJOgl6izoRljhQsTVl8Lqv5cQS5bK5JNxTAsp/z9nuHsIzDtwvGnodlCbrQSPyPUnQvdezTXhNp/OU4owzFGbTiRwgQoHqXDXXCAvzAWQ=,iv:7pHBkGXupzr5xjcv5r7gMwJq62ZUQ2T8pjgl9sOuLLg=,tag:JGn44KujFI9d4kMHtD9rcA==,type:str]
            error_reporting:
                enabled: false
            postgresql:
                password: ENC[AES256_GCM,data:7PUZvVIpch62kMDaeDBEifZ1oG4q/Rg6gkIKuk8VcFO2ApTcypKlmFxBHwjvf8nlvs+15DJ8A41YCCPnmuE8g/SkNWXfLWu5X7zAsfIMg3c=,iv:jcJ3rqiJzn3kI533q6Jna6VEAM563uc1WJRywfr/Iuw=,tag:saMPV/k5lJju8qps8PtNqw==,type:str]
        server:
            ingress:
                enabled: true
                hosts:
                    - auth.plasm.es
                tls:
                    - secretName: authentik-tls
                      hosts:
                        - auth.plasm.es
                annotations:
                    cert-manager.io/cluster-issuer: ovh
        postgresql:
            enabled: true
            auth:
                password: ENC[AES256_GCM,data:HXIT7Ee7e32UQ3BbOYvv38rPosY0J5rkTGWrASeRF3o3QSqlyZNlE7qbRU9IHjMx5OnF2gqH1vht9ZlAWGLMpiR5jRiXoyECdIq92mKirf8=,iv:PatVrlqVxd+o8XCf63XnZWx8yUMjRnyAgFYECw0L6Vc=,tag:b+ZclVnYXMU24T/2GF/ncQ==,type:str]
            primary:
                persistence:
                    storageClass: openebs-hostpath
        redis:
            enabled: true
            master:
                persistence:
                    storageClass: openebs-hostpath
sops:
    encrypted_regex: ^(data|stringData)$|password|secret_key
    lastmodified: "2026-10-08T10:58:57Z"
    mac: ENC[AES256_GCM,data:0hxUD5qfcYAE5nhlmPTsebjt9pKB91NQ9iSmeBUNLHkmsX3HMQB8u9Ox7jU/D7wCRVg3VguGqhUZexMzOhtwBiCf/a18vIfyDMItmZqVWiMlSxu0aqxLwGcIfLtDyfM5l3ivtmJpUdK10KfA/Ez+5UN5gXjeMByToTJFqRokTOQ=,iv:n+CsQmzwTWx4+/Kbfp7T0TuRKnPTj+WUyZ3LSt3MEuc=,tag:SKRhyqUNBke14OGSHA8Lcg==,type:str]
    pgp:
        - created_at: "2026-10-08T10:58:57Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DwW+vaVwrS2ISAQdAxCs2D5WaMZjss3u7ci8R7dBPMKnYHKWzDsXYXW6LMWgw
            RZzN58zjFPT7YJ+rr6joQPjTyRFhsWHLV1wfpYaqeZNAkc/oTCTxUtw+MsNeXO7x
            0l4BcKgan/Mm68A1/rwzI45/PuxDK4ZzviR/KqLooOKAoXYmBRW5kfp5odQwP9iB
            cwcnZSy9KRJ53yg56wLNHvXRd/QQSGfh1zd1vAOQtT73hmcGfeE9mV5dpoPJu7Ae
            =pA/P
            -----END PGP MESSAGE-----
          fp: B51175A0392C55BA3A9D508C914AB2CE60624E82
    version: 3.13.3
