apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
    name: authentik
    namespace: flux-system
spec:
    interval: 10m0s
    url: https://charts.goauthentik.io
sops:
    lastmodified: "2025-04-13T15:59:52Z"
    mac: ENC[AES256_GCM,data:OritVYFsDTuBnfEtWcy5d0MkBSNQ5hkvNW1/0FztzYp9GliLILJEQ2mOCaT/oECAfmNzxcAhKilPIlKdN7qIgwcWE6TxatB3mM6iA3g3n5wE2yEQJs2YgmnLc4E+x683s7hnss1X1jDm+ug3RrHjPXq2vByxEFMo9iR/wwgOrd8=,iv:USaZ12Aj0lnIEuXeAMMo3CjuEXIi8XawNfz6Oy+JmSk=,tag:IvidCX6kK9+ve0bkrVIEHw==,type:str]
    pgp:
        - created_at: "2025-04-13T13:37:26Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DwW+vaVwrS2ISAQdAwSKBAh6cJI0Rl15AGj4Hpn4jaET8V4ncksQiP37wuHEw
            nrCHWGUFrie8Yd+no92YrdrHFczq17ycU4+wLBs3vcuXn1uonoinfKT1thb0yuOE
            1GgBCQIQvfbzyYLTxRl6ZqWCT6FUEDhDUoGxx1aqGHmMzCbpaLCnGYqTlIbr+oBG
            DNDQ4kT7FMo5Hm2sAN7jKznJCMGwf2G5aG+SspgQ+ZYGZAxuhacdWGKJ6KKjX3/7
            VSieXX3jb63gaw==
            =VWXI
            -----END PGP MESSAGE-----
          fp: B51175A0392C55BA3A9D508C914AB2CE60624E82
    encrypted_regex: password|secret_key
    version: 3.10.1
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: authentik
    namespace: flux-system
spec:
    releaseName: authentik
    chart:
        spec:
            chart: authentik
            reconcileStrategy: ChartVersion
            sourceRef:
                kind: HelmRepository
                name: authentik
    targetNamespace: authentik
    install:
        createNamespace: true
        remediation:
            retries: 1
    interval: 10m0s
    values:
        authentik:
            secret_key: ENC[AES256_GCM,data:95gwhua4Ko67RFNpHs7frRoJiBvwgsPeS688D9SP4QzGssU4G+8pAmFdvtieAWY9FdMMiFV8kz7VgHCIvlKc+fnE4I5RmnK+BKmyn3h1vRM=,iv:L6v8XImRy4APmqFcgcnyTDYqibqv3GNhCoy6ddq7ruE=,tag:4fu31BCI81S6P0OTUViqnQ==,type:str]
            error_reporting:
                enabled: false
            postgresql:
                password: ENC[AES256_GCM,data:w7f4YHzmIj2cNBY0D1pijiKFMsQDDn984T2SeyLXx8eSEi3IHxHlKTWp50Ut6ORtYqjvWhcKgvJDXK9xQZiPZk/ercj4/tx/WNWSEewB+Iw=,iv:hVOUuOaCR6dHX/bv1tiKp0kKXt/Lsu/pQf5zZvTuZno=,tag:VzCLWD+sLxbd7mpb8eGdFg==,type:str]
        server:
            ingress:
                enabled: true
                hosts:
                    - auth.admin.ad
        postgresql:
            enabled: true
            auth:
                password: ENC[AES256_GCM,data:lSwZNAF/ISKdGXUNS6kB2tVSeuLU/elxQWddcpAwFDeT2Cr3+FYrbGzBbSPnTPCV/FuKHkkfhmFeT3sYNpQcX8kMICpXVe1i9k3k8FYa1wI=,iv:94TwA7z0spfpySdAKIkY8aJ212IOKuorlKGHjGswZ9s=,tag:U1VMCu9/KPnFLxpxAAzlcg==,type:str]
            primary:
                persistence:
                    storageClass: openebs-hostpath
        redis:
            enabled: true
            master:
                persistence:
                    storageClass: openebs-hostpath
sops:
    lastmodified: "2025-04-13T15:59:52Z"
    mac: ENC[AES256_GCM,data:OritVYFsDTuBnfEtWcy5d0MkBSNQ5hkvNW1/0FztzYp9GliLILJEQ2mOCaT/oECAfmNzxcAhKilPIlKdN7qIgwcWE6TxatB3mM6iA3g3n5wE2yEQJs2YgmnLc4E+x683s7hnss1X1jDm+ug3RrHjPXq2vByxEFMo9iR/wwgOrd8=,iv:USaZ12Aj0lnIEuXeAMMo3CjuEXIi8XawNfz6Oy+JmSk=,tag:IvidCX6kK9+ve0bkrVIEHw==,type:str]
    pgp:
        - created_at: "2025-04-13T13:37:26Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DwW+vaVwrS2ISAQdAwSKBAh6cJI0Rl15AGj4Hpn4jaET8V4ncksQiP37wuHEw
            nrCHWGUFrie8Yd+no92YrdrHFczq17ycU4+wLBs3vcuXn1uonoinfKT1thb0yuOE
            1GgBCQIQvfbzyYLTxRl6ZqWCT6FUEDhDUoGxx1aqGHmMzCbpaLCnGYqTlIbr+oBG
            DNDQ4kT7FMo5Hm2sAN7jKznJCMGwf2G5aG+SspgQ+ZYGZAxuhacdWGKJ6KKjX3/7
            VSieXX3jb63gaw==
            =VWXI
            -----END PGP MESSAGE-----
          fp: B51175A0392C55BA3A9D508C914AB2CE60624E82
    encrypted_regex: password|secret_key
    version: 3.10.1
