apiVersion: v1
kind: Service
metadata:
  name: homeassistant-metrics
  labels:
    app: homeassistant-metrics
spec:
  ports:
  - name: http-metrics
    port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: homeassistant-metrics
subsets:
- addresses:
  - ip: 192.168.1.20
  ports:
  - name: http-metrics
    port: 80
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: homeassistant
  labels:
    release: kube-prometheus-stack
spec:
  endpoints:
  - interval: 30s
    path: /api/prometheus
    port: http-metrics
    bearerTokenSecret:
      name: homeassistant-prometheus-token
      key: token
  selector:
    matchLabels:
      app: homeassistant-metrics
