apiVersion: v1
data:
    token: ENC[AES256_GCM,data:qtAZ8Lo3KXlZl7Pdf2uY+Mw/PZUtBvLmdkG/He9K/U+VWWge5DeKZMa3rmVFwR2CgsR6PiLZfBDXbefPjbBibfgmJiZuHsjRYGilWakcXOSQYMgw0QAEKaGHSuEm+LajAAWwGL0pc0KfhNShaSn20ytpl2HOZEljgq96FcSsCLkLZ65LfhEl5f4Y3GRsUVsmufenwjQKBWaGQoOwvmOScP0RsvYuTLdCyidwjJv5sjq9GaT+zxa8ckislD1xw1QzrcKMoWGiWPp5wO69ePRpfOGdhLws7Fk2vBvJSqXg7EtPlNTVQmBhemjI59TUAaZun90QlQ==,iv:3VewZKR6t9n29vkLhZsiaWqOt1oFlydD8JZCBme8PmI=,tag:koMDS1tx5SptlAdSMdM7Vw==,type:str]
kind: Secret
metadata:
    name: homeassistant-prometheus-token
    namespace: prometheus-stack
type: Opaque
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-08T10:58:58Z"
    mac: ENC[AES256_GCM,data:hjGdGWbmirQ2VnKGBROwQFKaUmaEmBo4ldjZmHS0LktmS5hcXH6r+gKyWVtLwkqhJ6ZL3AKTbj1BM8Hui3ECmd13OosClqV3tQh//P68+K87O5OqbSMarr/oXJrtJ8QaY7jYzVc/mrom2h4NUcSHh886X2lrKwI55ZlJyHgJ2NA=,iv:wv0IHGvRqfbnYFXLbx5P/Pjkuo5nkizty+vw6GxD+hI=,tag:UM/PT8FnWr2U0j0LsnkgwQ==,type:str]
    pgp:
        - created_at: "2026-10-08T10:58:58Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DwW+vaVwrS2ISAQdA6wYLuYHGlfTQ0Tlerd7yTsvs1dPt8tpgLw0JZH6ik0cw
            IdceMiJVSxwH7Ie/Jctlme6U5ZJ8iAZDC4FqR3TojMrXs4wgjdAZVmGmxf7+WwoJ
            0l4BMfoBhl/18uUgeOMT6YvwPaczTVM326t2P0W3kTw8LNTf9MU0zeHrC3cceQFD
            aWB9VlZAmZmew4VAtrE9c6UFwx4DA2x1P1W8ZMLFk5pALFOPzPROPwxeynL8iCrT
            =5S97
            -----END PGP MESSAGE-----
          fp: B51175A0392C55BA3A9D508C914AB2CE60624E82
    version: 3.13.3
