---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: ollama-helm
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://otwld.github.io/ollama-helm/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ollama
  namespace: flux-system
spec:
  releaseName: ollama
  chart:
    spec:
      chart: ollama
      version: "1.46.0"
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: ollama-helm
  targetNamespace: ollama
  install:
    createNamespace: true
    remediation:
      retries: 1
  interval: 10m0s
  values:
    ollama:
      gpu:
        enabled: false
      models:
        pull:
          - "smollm:135m"
        run:
          - "smollm:135m"
      mountPath: ""

    resources:
      requests:
        memory: "1024Mi"
        cpu: "500m"
      limits:
        memory: "1536Mi"
        cpu: "1000m"

    persistentVolume:
      enabled: true
      storageClass: "openebs-hostpath"
      size: 30Gi

    # --- Ingress configuration (añadido) ---
    ingress:
      enabled: true
      className: traefik
      annotations:
        cert-manager.io/cluster-issuer: "ovh"
      hosts:
        - host: ollama.plasm.es
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - ollama.plasm.es
          # asegúrate de que este secret exista o de que cert-manager lo cree
          secretName: ollama-plasm-es-tls
