apiVersion: v1
kind: Secret
metadata:
    name: frigate-mqtt-credentials
    namespace: frigate
type: Opaque
stringData:
    FRIGATE_MQTT_USER: ENC[AES256_GCM,data:x1KHVbtrFA==,iv:DdZoy6WRH+1FuK0ri13m/nrRWSzNKE4oHtNLKEvFKqw=,tag:nhCJWZXTTSQ74n99TVw6ig==,type:str]
    FRIGATE_MQTT_PASSWORD: ENC[AES256_GCM,data:DGPhcgXMX7PuHXgFD98rSi2SgpBj,iv:6YB7aocYJyRPiCJlP78jD48Fw20n231/2eJLejNtBYE=,tag:rLP4o50pK76oRxLhwi4rcA==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-08T11:34:52Z"
    mac: ENC[AES256_GCM,data:eg6E2U2ZbKLPX6Uu/cHhW7AkDG/H2OzQLjH1/MfeIUhtIpmjsd5O2vn/4u2JFJo7qpt0KxMpE8WhI8KCO3femo9lh/8Zmk8NkLGlUbCs55aeghyT21UOdscDFwaSX6XoChWWMsiCbt+pDI4+YWGINuZMihtODGmMNRdV+x2DEcI=,iv:YRoRPyQyusjCSyexkP7jP2eiFQkn0yv1NQjx2547BSI=,tag:jxRSovrUnPWaeMtqOuyhhg==,type:str]
    pgp:
        - created_at: "2026-10-08T11:34:52Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DwW+vaVwrS2ISAQdAo9qQzQUvqP60mMHaM3YdwxuP1huysyIqxhkmIkP+YWsw
            O/fncjDCxtA4flIkHNysKC+A4NeuWiptrCofyfiw0fcOQuOknsEyvraP4K/Vusjm
            0l4Be98NvqHMGkIndvofOxVCDVd6pJhKdYZEfxIyI2WLrxA+2KRKbjUpm5fEOH87
            my4bzT4j//48idDvnkLGlmWrTAUK2hoBCj4RCmarz9GLWcibJ9FH0RNlt0PMmnW0
            =YPPf
            -----END PGP MESSAGE-----
          fp: B51175A0392C55BA3A9D508C914AB2CE60624E82
    version: 3.13.3
