---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: frigate
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://blakeblackshear.github.io/blakeshome-charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: frigate
  namespace: flux-system
spec:
  releaseName: frigate
  chart:
    spec:
      chart: frigate
      version: '7.8.0'
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: frigate
  targetNamespace: frigate
  install:
    createNamespace: true
    remediation:
      retries: 1
  interval: 10m0s
  values:
    image:
      tag: 0.16.2
    ingress:
      enabled: true
      hosts: 
        - host: frigate.plasm.es
          paths:
            - path: '/'
              portName: http
      tls:
        - secretName: "firgate-tls"
          hosts:
            - frigate.plasm.es
      annotations:
        cert-manager.io/cluster-issuer: ovh
    persistence:
      media:
        enabled: true
        storageClass: "openebs-hostpath"
    config: |
      mqtt:
        enabled: false

      detectors:
        ov:
          type: openvino
          device: CPU

      model:
        width: 300
        height: 300
        input_tensor: nhwc
        input_pixel_format: bgr
        path: /openvino-model/ssdlite_mobilenet_v2.xml
        labelmap_path: /openvino-model/coco_91cl_bkgr.txt

      go2rtc:
        streams:
          smar1:
            - rtsp://admin:admin@192.168.1.30:554/channel=0_stream=0&onvif=0.sdp?real_stream
            - ffmpeg:back#audio=acc
          smar1_sub:
            - rtsp://admin:admin@192.168.1.30:554/channel=0_stream=1&onvif=0.sdp?real_stream
            - ffmpeg:back#audio=acc 
          smar2:
            - rtsp://admin:admin@192.168.1.31:554/channel=0_stream=0&onvif=0.sdp?real_stream
            - ffmpeg:back#audio=acc
          smar2_sub:
            - rtsp://admin:admin@192.168.1.31:554/channel=0_stream=1&onvif=0.sdp?real_stream
            - ffmpeg:back#audio=acc 
      record:
        enabled: True
        retain:
          days: 3
          mode: motion
      snapshots:
        # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
        enabled: True
        # Optional: save a clean PNG copy of the snapshot image (default: shown below)
        clean_copy: True
        # Optional: print a timestamp on the snapshots (default: shown below)
        timestamp: True
        # Optional: draw bounding box on the snapshots (default: shown below)
        bounding_box: True
        # Optional: crop the snapshot (default: shown below)
        crop: False
        # Optional: quality of the encoded jpeg, 0-100 (default: shown below)
        quality: 70
      cameras:
        smar1: # <------ Name the camera
          enabled: true
          ffmpeg:
            output_args:
              record: preset-record-generic-audio-copy
            inputs:
              - path: rtsp://127.0.0.1:8554/smar1 # <----- The stream you want to use for detection
                input_args: preset-rtsp-restream
                roles:
                  - record
              - path: rtsp://127.0.0.1:8554/smar1_sub
                input_args: preset-rtsp-restream
                roles:
                  - detect
          detect:
            enabled: true # <---- disable detection until you have a working camera feed
            width: 1280
            height: 720
        smar2: # <------ Name the camera
          enabled: true
          ffmpeg:
            output_args:
              record: preset-record-generic-audio-copy
            inputs:
              - path: rtsp://127.0.0.1:8554/smar2 # <----- The stream you want to use for detection
                input_args: preset-rtsp-restream
                roles:
                  - record
              - path: rtsp://127.0.0.1:8554/smar2_sub
                input_args: preset-rtsp-restream
                roles:
                  - detect
          detect:
            enabled: true # <---- disable detection until you have a working camera feed
            width: 1280
            height: 720

