---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cert-manager-webhook-ovh
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://aureq.github.io/cert-manager-webhook-ovh/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager-webhook-ovh
  namespace: flux-system
spec:
  releaseName: cert-manager-webhook-ovh
  chart:
    spec:
      chart: cert-manager-webhook-ovh
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: cert-manager-webhook-ovh
  targetNamespace: cert-manager
  install:
    createNamespace: true
    remediation:
      retries: 1
  interval: 10m0s
  values:
    configVersion: 0.0.1
    issuers:
      - name: ovh
        create: true
        kind: ClusterIssuer
        email: muchorrollodejavi@gmail.com
        acmeServerUrl: https://acme-v02.api.letsencrypt.org/directory
        ovhEndpointName: ovh-eu
        ovhAuthenticationRef:
          applicationKeyRef:
            name: ovh-credentials
            key: OVH_APPLICATION_KEY
          applicationSecretRef:
            name: ovh-credentials
            key: OVH_APPLICATION_SECRET
          consumerKeyRef:
            name: ovh-credentials
            key: OVH_CONSUMER_KEY

