---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: openclaw-helm
  namespace: flux-system
spec:
  interval: 1h
  url: https://serhanekicii.github.io/openclaw-helm/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openclaw
  namespace: flux-system
spec:
  releaseName: openclaw
  chart:
    spec:
      chart: openclaw
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: openclaw-helm
  targetNamespace: openclaw
  install:
    createNamespace: true
    remediation:
      retries: 3
  interval: 10m0s
  values:
    app-template:
      configMaps:
        config:
          # @schema type:boolean;default:true
          enabled: true
          data:
            # Shell alias for interactive sessions (sourced by ~/.bashrc)
            # @schema type:string
            bash_aliases: |
              alias openclaw='node /app/dist/index.js'
            # OpenClaw configuration - JSON5 format
            # Sensitive values use ${ENV_VAR} substitution from environment secret
            # @schema type:string
            openclaw.json: |
              {
                // Gateway configuration
                "gateway": {
                  "port": 18789,
                  "mode": "local",
                  // IMPORTANT: trustedProxies uses exact IP matching only
                  // - CIDR notation is NOT supported - list each proxy IP individually
                  // - IPv6 exact addresses may work but are untested
                  // - Recommend single-stack IPv4 deployments for simplicity
                  "trustedProxies": ["10.0.0.1"],
                  "controlUi": {
                    "dangerouslyAllowHostHeaderOriginFallback": true
                  }
                },

                // Browser configuration (Chromium sidecar)
                "browser": {
                  "enabled": true,
                  "defaultProfile": "default",
                  "profiles": {
                    "default": {
                      "cdpUrl": "http://localhost:9222",
                      "color": "#4285F4"
                    }
                  }
                },

                // Agent configuration
                "agents": {
                  "defaults": {
                    "workspace": "/home/node/.openclaw/workspace",
                    "model": {
                      // Uses ANTHROPIC_API_KEY from environment
                      "primary": "anthropic/claude-opus-4-6"
                    },
                    "userTimezone": "UTC",
                    "timeoutSeconds": 600,
                    "maxConcurrent": 1
                  },
                  "list": [
                    {
                      "id": "main",
                      "default": true,
                      "identity": {
                        "name": "OpenClaw",
                        "emoji": "🦞"
                      }
                    }
                  ]
                },

                // Session management
                "session": {
                  "scope": "per-sender",
                  "store": "/home/node/.openclaw/sessions",
                  "reset": {
                    "mode": "idle",
                    "idleMinutes": 60
                  }
                },

                // Logging
                "logging": {
                  "level": "debug",
                  "consoleLevel": "debug",
                  "consoleStyle": "compact",
                  "redactSensitive": "tools"
                },

                // Tools configuration
                "tools": {
                  "profile": "full",
                  "web": {
                    "search": {
                      "enabled": false
                    },
                    "fetch": {
                      "enabled": true
                    }
                  }
                }

                // Channel configuration can be added here:
                // "channels": {
                //   "telegram": {
                //     "botToken": "${TELEGRAM_BOT_TOKEN}",
                //     "enabled": true
                //   },
                //   "discord": {
                //     "token": "${DISCORD_BOT_TOKEN}"
                //   },
                //   "slack": {
                //     "botToken": "${SLACK_BOT_TOKEN}",
                //     "appToken": "${SLACK_APP_TOKEN}"
                //   }
                // }
              }
      persistence:
        data:
          enabled: true
          storageClass: "openebs-hostpath"
          size: 1Gi
          accessMode: ReadWriteOnce
      # Configuración del Ingress para OpenClaw
      ingress:
        main:
          enabled: true
          annotations:
            cert-manager.io/cluster-issuer: ovh
          hosts:
            - host: openclaw.plasm.es
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - hosts:
                - openclaw.plasm.es
              secretName: openclaw-plasm-es-tls
      controllers:
        main:
          containers:
            main:
              env:
                GATEWAY_CONTROLUI_ALLOWEDORIGINS: '["https://openclaw.plasm.es"]'
                GATEWAY_CONTROLUI_DANGEROUSLYALLOWHOSTHEADERORIGINFALLBACK: true
